"""Regression tests for serializing a workspace right after a GitHub (dis)connect.

``Workspace.updated_at`` is generated by the database (``onupdate=func.now()``).
The UPDATE emitted by ``AsyncSession.flush()`` does not ask for that value back
(the mapper's ``eager_defaults`` defaults to ``"auto"``), so SQLAlchemy expires
``updated_at`` on the instance. Reading it afterwards from Pydantic's
``from_attributes`` serialization triggers a lazy load outside ``greenlet_spawn``
and fails with ``MissingGreenlet``. The workspace service must reload the column
inside the active async session before returning the ORM object.
"""

import asyncio
import datetime
import uuid
from collections.abc import AsyncIterator, Iterable, Iterator
from unittest.mock import AsyncMock, patch

import pytest
from app.api.dependencies import get_accessible_workspace, get_owned_workspace
from app.core.database import get_db
from app.integrations.github.client import github_client
from app.main import app
from app.models.workspace import Workspace
from app.schemas.workspace import WorkspaceResponse
from fastapi.testclient import TestClient
from pydantic import ValidationError
from sqlalchemy import inspect as sa_inspect
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import make_transient_to_detached

INSTALLATION_ID = 998877
UNUSED_DATABASE_URL = "postgresql+psycopg://unused:unused@127.0.0.1:1/unused"


class PostgresLikeSession:
    """Async session double mirroring PostgreSQL's UPDATE-without-RETURNING behaviour.

    A real ``AsyncSession`` is used for its greenlet-aware lazy loading, but the
    engine is never connected: an attempt to load an expired attribute therefore
    fails with ``MissingGreenlet`` (the production symptom) instead of any SQL.
    """

    def __init__(self) -> None:
        self._engine = create_async_engine(UNUSED_DATABASE_URL)
        self.async_session = AsyncSession(bind=self._engine, expire_on_commit=False)
        self.refreshed_attributes: list[tuple[str, ...]] = []

    def attach(self, workspace: Workspace) -> None:
        """Attach ``workspace`` as if it had just been loaded from the database (no SQL)."""
        make_transient_to_detached(workspace)
        self.async_session.sync_session.add(workspace)

    async def flush(self) -> None:
        for obj in (*self.async_session.sync_session.new, *self.async_session.sync_session.dirty):
            if sa_inspect(obj).persistent:
                # PostgreSQL persists ``onupdate=func.now()`` on UPDATE but only sends
                # it back when RETURNING is used, which leaves the column expired here.
                self.async_session.sync_session.expire(obj, ["updated_at"])

    async def refresh(self, instance: object, attribute_names: Iterable[str] | None = None) -> None:
        names = tuple(attribute_names) if attribute_names is not None else ("updated_at",)
        self.refreshed_attributes.append(names)
        for name in names:
            setattr(instance, name, datetime.datetime.now(datetime.UTC))

    async def commit(self) -> None:
        pass

    async def rollback(self) -> None:
        pass

    def close(self) -> None:
        self.async_session.sync_session.close()


@pytest.fixture()
def session_double() -> Iterator[PostgresLikeSession]:
    double = PostgresLikeSession()
    yield double
    double.close()


@pytest.fixture()
def workspace() -> Workspace:
    now = datetime.datetime.now(datetime.UTC)
    workspace = Workspace(name="Test Workspace")
    workspace.id = uuid.uuid4()
    workspace.github_installation_id = None
    workspace.created_at = now
    return workspace


@pytest.fixture()
def client(session_double: PostgresLikeSession, workspace: Workspace) -> Iterator[TestClient]:
    session_double.attach(workspace)

    async def override_get_db() -> AsyncIterator[PostgresLikeSession]:
        try:
            yield session_double
            await session_double.commit()
        except Exception:
            await session_double.rollback()
            raise

    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_owned_workspace] = lambda: workspace
    app.dependency_overrides[get_accessible_workspace] = lambda: workspace
    with TestClient(app) as test_client:
        yield test_client
    app.dependency_overrides.clear()


def test_connect_endpoint_response_serializes_updated_at(
    client: TestClient, session_double: PostgresLikeSession, workspace: Workspace
) -> None:
    """The connect endpoint must serialize the flushed workspace without IO in the handler."""
    with patch.object(
        github_client, "list_installation_repositories", new=AsyncMock(return_value=[])
    ):
        response = client.post(
            f"/api/v1/workspaces/{workspace.id}/github/connect",
            json={"installation_id": INSTALLATION_ID},
        )

    assert response.status_code == 200, response.text
    data = response.json()
    assert data["github_installation_id"] == INSTALLATION_ID
    assert data["is_github_connected"] is True
    assert datetime.datetime.fromisoformat(data["updated_at"])
    # the service reloaded the database-generated column inside the async session
    assert session_double.refreshed_attributes == [("updated_at",)]


def test_workspace_response_reproduces_missing_greenlet(
    session_double: PostgresLikeSession, workspace: Workspace
) -> None:
    """Characterize the production failure: an expired column cannot load outside a greenlet."""
    session_double.attach(workspace)
    asyncio.run(session_double.flush())
    assert "updated_at" in sa_inspect(workspace).expired_attributes

    with pytest.raises(ValidationError) as exc_info:
        WorkspaceResponse.model_validate(workspace)

    assert "updated_at" in str(exc_info.value)
    assert "MissingGreenlet" in str(exc_info.value)
